# https://taskfile.dev
version: '3'

vars:
  STARTUP_PATH: "./src/Fanoos.Api"
  PROJECT_PATH: "./src/Fanoos.Infrastructure"

dotenv:
  - .env

tasks:
  default: task --list-all

  restore: dotnet restore ./Fanoos.slnx

  run:
    aliases: [ r ]
    desc: Run the project
    cmds:
      - dotnet run --project ./src/Fanoos.Api/ --no-restore

  migrate:
    aliases: [ m ]
    desc: Generate & run EF migrations.
    cmds:
      - task: migration:generate
      - task: migration:apply

  migration:generate:
    aliases: [ mg ]
    desc: Generate EF migrations.
    cmds:
      - dotnet ef migrations add {{.MIGRATION_NAME}} -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}}
    requires:
      vars: [ MIGRATION_NAME, PROJECT_PATH, STARTUP_PATH ]

  migration:apply:
    aliases: [ ma ]
    desc: Run EF migrations.
    cmds:
      - dotnet ef database update -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}}
    requires:
      vars: [ PROJECT_PATH, STARTUP_PATH ]
