# https://taskfile.dev
version: '3'

vars:
  ASPNETCORE_ENVIRONMENT: Development
  PROJECT_PATH: "./src/Fanoos.Infrastructure"
  SOLUTION_FILE_PATH: "./Fanoos.slnx"
  STARTUP_PATH: "./src/Fanoos.Api"

tasks:
  default:
    desc: List all the tasks.
    cmds:
      - task --list-all

  dotnet:dev:
    aliases: [ d ]
    desc: Run the project in dev mode
    cmds:
      - dotnet run --project {{.STARTUP_PATH}} --no-restore
    requires:
      vars: [ STARTUP_PATH ]

  dotnet:restore:
    aliases: [ r ]
    desc: Restore the whole solution.
    cmds:
      - dotnet restore {{.SOLUTION_FILE_PATH}}
    requires:
      vars: [ SOLUTION_FILE_PATH ]

  dotnet:format:
    aliases: [ f ]
    desc: Format the project
    cmds:
      - dotnet format {{.SOLUTION_FILE_PATH}}
    requires:
      vars: [ SOLUTION_FILE_PATH ]

  dotnet:build:
    aliases: [ b ]
    desc: Build the project
    cmds:
      - dotnet build {{.SOLUTION_FILE_PATH}}
    requires:
      vars: [ SOLUTION_FILE_PATH ]

  migration:all:
    aliases: [ m ]
    desc: Generate & run EF migrations.
    cmds:
      - task: migration:generate
      - task: migration:apply

  migration:generate:
    aliases: [ mg ]
    desc: Generate EF migrations.
    cmds:
      - dotnet ef migrations add {{.MIGRATION_NAME}} -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}}
    requires:
      vars: [ MIGRATION_NAME, PROJECT_PATH, STARTUP_PATH ]

  migration:apply:
    aliases: [ ma ]
    desc: Run EF migrations.
    cmds:
      - dotnet ef database update -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}}
    requires:
      vars: [ PROJECT_PATH, STARTUP_PATH ]

  docker:up:
    desc: Start all services (detached)
    cmds:
      - docker compose up -d

  db:shell:
    desc: Open psql shell inside container
    interactive: true
    cmds:
      - docker exec -it fanoos.db psql -U postgres -d fanoos
