# https://taskfile.dev
version: '3'

vars:
  STARTUP_PATH: "./src/Fanoos.Api"
  PROJECT_PATH: "./src/Fanoos.Infrastructure"

tasks:
  list-all:
    aliases: [ default ]
    desc: List all the tasks.
    cmds:
      - task --list-all

  dev:
    aliases: [ d ]
    desc: Run the project in dev mode
    cmds:
      - dotnet run --project ./src/Fanoos.Api/ --no-restore

  restore:
    aliases: [ r ]
    desc: Restore the whole solution.
    cmds:
      - dotnet restore ./Fanoos.slnx

  format:
    aliases: [ f ]
    desc: Format the project
    cmds:
      - dotnet format ./Fanoos.slnx

  build:
    aliases: [ b ]
    desc: Build the project
    cmds:
      - dotnet build ./Fanoos.slnx

  migrate:
    aliases: [ m ]
    desc: Generate & run EF migrations.
    cmds:
      - task: migration:generate
      - task: migration:apply

  migration:generate:
    aliases: [ mg ]
    desc: Generate EF migrations.
    cmds:
      - dotnet ef migrations add {{.MIGRATION_NAME}} -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}}
    requires:
      vars: [ MIGRATION_NAME, PROJECT_PATH, STARTUP_PATH ]

  migration:apply:
    aliases: [ ma ]
    desc: Run EF migrations.
    cmds:
      - dotnet ef database update -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}}
    requires:
      vars: [ PROJECT_PATH, STARTUP_PATH ]

  dc:up:
    desc: Start all services (detached)
    cmds:
      - docker compose up -d

  dc:down:
    desc: Stop all services (keep volumes)
    cmds:
      - docker compose down

  dc:restart:
    desc: Restart services
    cmds:
      - task down
      - task up

  dc:reset:
    desc: ⚠️ Stop and delete database data folder
    cmds:
      - docker compose down
      - rm -rf ./.containers/
      - mkdir -p ./.containers/
      - docker compose up -d

  dc:db:shell:
    desc: Open psql shell inside container
    interactive: true
    cmds:
      - docker exec -it fanoos.db psql -U postgres -d fanoos
