# https://taskfile.dev
version: '3'

tasks:

  # ---- meta ----
  meta:list:
    aliases: [ default ]
    desc: List all tasks
    cmds:
      - task --list-all

  # ---- app ----
  app:dev:
    aliases: [ dev, d ]
    desc: Start Vite dev server
    cmds:
      - npm run vite

  app:preview:
    desc: Preview production build
    cmds:
      - npm run vite -- preview

  app:type-check:
    aliases: [ t ]
    desc: Run TypeScript type checking
    cmds:
      - npm run vue-tsc -- --build

  app:build:full:
    desc: Type-check then build project
    cmds:
      - task: app:type-check
      - task: app:build:only

  app:build:only:
    desc: Build project without type checking
    cmds:
      - npm run vite -- build

  # ---- api ----
  api:def:
    aliases: [ acgd ]
    desc: Download OpenAPI definition
    cmds:
      - curl -o "./src/common/api/openapi.yaml" "http://localhost:5000/openapi.yaml"

  api:gen:
    aliases: [ acg ]
    desc: Generate API client
    cmds:
      - npm run openapi-ts

  api:all:
    desc: Refresh API client (definition + generate)
    cmds:
      - task: api:def
      - task: api:gen

  # ---- test ----
  test:unit:
    desc: Run unit tests with Vitest
    cmds:
      - npm run vitest

  # ---- lint ----
  lint:all:
    aliases: [ l ]
    desc: Run all linters sequentially
    cmds:
      - task: lint:ox
      - task: lint:eslint

  lint:ox:
    desc: Lint with Oxlint (auto-fix)
    cmds:
      - npm run oxlint -- . --fix

  lint:eslint:
    desc: Lint with ESLint (auto-fix + cache)
    cmds:
      - npm run eslint -- . --fix --cache

  # ---- format ----
  quality:format:
    aliases: [ f ]
    desc: Format files with Oxfmt
    cmds:
      - npm run oxfmt -- ./src/
